# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Bhanu Kamapantula
tagline: On software, management, technology, society
description: I'm interested in the impact of Technology, People, Data, Society, Art on one another.
author: Bhanu Kamapantula
github_username: bkamapantula
url: https://bkamapantula.github.io/
lang: en

# Email and twitter are optional:
twitter_username: thoughtisdead
rss: rss

social:
  links:
    - https://twitter.com/thoughtisdead
    - https://github.com/bkamapantula/
    - https://www.linkedin.com/in/bkamapantula/

header_pages:
  - about.md
  - art.md
  - news.md
show_excerpts: true

# Set this to true to get LaTeX math equation support
use_math: false

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: posts/page:num/


####
# staticman
####
# all of these fields are nested under the comments key, which corresponds to the final element
# of the API bridge enpoint, i.e., you can different configurations even within the same staticman.yml
# file all under different keys
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://staticman-bkamapantula-github.herokuapp.com/v2/entry/bkamapantula/bkamapantula.github.io/master/comments

reCaptcha:
    enabled: true
    # v2
    siteKey: 6Lf2lbAZAAAAAFiJXzDQ8SB783VWRDDKjpaflLbN
    secret: Iv6I9TYLULu88UmmevAKID/5MBX3BrcC/cFPLNWRnYGdelmx/9DSm1GQXxRn3q4zo7Go0ZL6BNAA9ib2DsRNGvUClMhDDczagwLHiVyFfiMC6uh3r8LkleLxzWe77njrpS8j0C4QkvGL7RSS/QrZJhUFqEvaXxtOlZkbXFlHoDvJBcJBYbNl5Pzdn/+8U8vU3J5Wo1C/789rNYG+n5gWy4VbpO4kMa1FlNNHIl7H8o31hE+SG48G/wx2LY6pGWaNohHrq4J4bZ4yrZ0yXUt6Y2MeYfLB7ad8RzODnkjmDVBOaQWu7V0TRScfHDR1egMeOZ8PxkpLiDdO7MQgpPt9CUovlN9Pq6QT24+/62lO3hgJw/GTdVSCAaDlMvJwLeY8NdksvFhxaRFg4im31EJfQmUAp/HgqXiz/IwajtVPAOuJ/+0F3R9syAqal9fK7fT4Gp/xgbmJge+LZ27fdKgjnCWQRzFuh65k4Qt6ItP1emkX4LvY/pGtMjwJVLppwAVBAprY1rvCSTbQyWgZPW3pI5znr50w8JmAh5U6/MkGK2Up8osPMTMaaP4dR19fQlN687m86wQf8P7kXxuotARgz4vUmbb7Z/T+b66wD7l/HDX7tny8JzJLFTZLTNAhJoGJcGim4L0tCCiXMKh16fN7Gcwcrch8fh96Bs0nNna3L0w=
    
