# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Bhanu Kamapantula
tagline: On software, management, technology, society
description: I'm interested in the impact of Technology, People, Data, Society, Art on one another.
github_username: bkamapantula
url: https://bkamapantula.github.io/
lang: en

# Email and twitter are optional:
email: 
twitter_username: thoughtisdead

social:
  links:
    - https://twitter.com/thoughtisdead
    - https://github.com/bkamapantula/
    - https://www.linkedin.com/in/bkamapantula/

header_pages:
  - about.md
  - art.md
show_excerpts: true

# Set this to true to get LaTeX math equation support
use_math: false

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
