# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Bhanu Kamapantula
tagline: On software, management, technology, society
description: I'm interested in the impact of Technology, People, Data, Society, Art on one another.
author: Bhanu Kamapantula
github_username: bkamapantula
url: https://bkamapantula.github.io/
lang: en

# Email and twitter are optional:
twitter_username: thoughtisdead
rss: rss

social:
  links:
    - https://twitter.com/thoughtisdead
    - https://github.com/bkamapantula/
    - https://www.linkedin.com/in/bkamapantula/

header_pages:
  - about.md
  - art.md
  - news.md
show_excerpts: true

# Set this to true to get LaTeX math equation support
use_math: false

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: posts/page:num/


####
# staticman
####
# all of these fields are nested under the comments key, which corresponds to the final element
# of the API bridge enpoint, i.e., you can different configurations even within the same staticman.yml
# file all under different keys
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://staticman-bkamapantula-github.herokuapp.com/v2/entry/bkamapantula/bkamapantula.github.io/master/comments

reCaptcha:
    enabled: true
    # v2
    siteKey: 6Lf2lbAZAAAAAFiJXzDQ8SB783VWRDDKjpaflLbN
    secret: s7JDeFxoz+4OxxNknABrpoXGa0BzIJ50Rp3RmOTg6iwWe/ue/mEonEGPbjJVv4LMyaEYVqTGyks9C+AYlcqYgbbJ9n1AuiK+gtcPW0b4X45X2RPbYPOAfH6/q+gERU+9lDqBdpuquKl/IAyjI3I4gB7JI7pbis56f8J+0ePEmw59TUhqoC8iBUu3wJqvgcsXYKB1yvHaRfHPQRcRJRki1qhMKTNZnNMZ2UtS3OI2WyTwva2DwO7CIXrCd6ler2im0FsQKptZpFy1kzqI7JtKJuL1LnG4RhSr0PgUH8+xCtQZEt1LFFMHqy2O885r56fynpVV1Q2/+2fOurU0zt3NfGJ7PpyTXbvQP1Kmt9bm/v4zRY5q0BOt1AHeDyldI5G70aafOxW3ysw7ZEgBjBLmu0LIlWlRYIUOJ9iXCNbWmZhTFPNmsFbEDqjZc+AP4cILwgnDiygwGxq1oZ1ho6NtJ38cwMmOBJZ8uBN8rmqKzWoLNVjJP+53bG2bOu/qnGgVFfxjqxhnif0WsVXIXrIm7apdcb4I9mI5N5n2po8Vafhowyf9sD0Ar9A7WwSCCn0JiGvCfPpCAY/8yomHl/DyDO6588paZVADqRLdW9cqqgXC60zWDIdmCqovt7ARu8FTnbCtGwSk2WppXgb9o4hSchZ7E51XW/mzi9t7P1skf6Y=
    
